### ISSUE TITLE
Bold text in markdown indistinguishable

### ISSUE THREAD

**Issue by olivermagnanimous** [dobestan/jupyter-notebook-themes#3]
If you zoom in really close, you can see a difference between bold and non-bold text, but it's not noticeable normally. Lora's bold and regular versions are quite different, so don't know what the issue is.

![screen shot 2017-05-05 at 18 04 15](https://cloud.githubusercontent.com/assets/26772530/25757367/0c09d682-31c2-11e7-824f-f59075e90209.png)

"time series" is bold

**Comment by olivermagnanimous** [comment]
Ok guess what, I found a solution. My knowledge in this area is pretty basic, but the issue gets fixed if you add this to the CSS files. 👍 

```css
@font-face {
 font-family: 'Lora';
 font-weight: bold;
 font-style: normal;
 src: local('Lora'), url('fonts/Lora-Bold.ttf') format('truetype');
}
```
